"""empty message

Revision ID: cab4da051ac0
Revises: ff09d9c55e32
Create Date: 2024-04-16 19:32:24.931419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab4da051ac0'
down_revision = 'ff09d9c55e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('gender')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
